-------------------------------------------------------------
-------------------------------------------------------------
CREATE TABLE public.twitter_videos_copy
(
    id uuid NOT NULL,
    url text COLLATE pg_catalog."default",
    date_processed_utc timestamp without time zone NOT NULL,
    tweet_with_video_id bigint NOT NULL,
    requesting_tweet_id bigint NOT NULL,
    requested_by text COLLATE pg_catalog."default",
    slug text COLLATE pg_catalog."default",
    CONSTRAINT pk_twitter_videos_copy PRIMARY KEY (id)
)
----------------------------------------------------------
INSERT INTO public.twitter_videos_copy
SELECT * FROM public.twitter_videos
----------------------------------------------------------
truncate table public.twitter_videos CASCADE
----------------------------------------------------------
-- Run migration script right here
----------------------------------------------------------
insert into public.twitter_videos
select v.id, v.url, v.date_processed_utc, v.tweet_with_video_id, slug from 
(
select min(requesting_tweet_id) requesting_tweet_id
from public.twitter_videos_copy
group by tweet_with_video_id
	) t
 inner join public.twitter_videos_copy v
 on v.requesting_tweet_id = t.requesting_tweet_id
----------------------------------------------------------
insert into public.twitter_video_requests
select gen_random_uuid(),vc.date_processed_utc,vc.requested_by,vc.requesting_tweet_id, v.id video_id
from public.twitter_videos_copy vc
inner join public.twitter_videos v 
on v.parent_tweet_id = vc.tweet_with_video_id
----------------------------------------------------------
select * from public.twitter_video_requests
select * from public.twitter_video
----------------------------------------------------------