version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore omniscraper/Omniscraper.Daemon/Omniscraper.Daemon.csproj
  build:
    commands:
      - echo Build started on `date`
      - cd omniscraper/Omniscraper.Daemon
      - dotnet publish -c release -o omniscraper-release
artifacts:
  files:
    - omniscraper/Omniscraper.Daemon/omniscraper-release/**/*
  name: omniscraper-daemon-$(date +%Y-%m-%d)-$CODEBUILD_BUILD_NUMBER.zip
  discard-paths: yes